[versions]

compose_version = '1.0.2'
kotlin_version = '1.5.21'
gradle_version = '7.1.0-alpha13'
dagger_version = '2.39.1'
retrofit_version = '2.9.0'
okhttp_version = '4.9.2'

[libraries]

compose-ui-core = { group = 'androidx.compose.ui', name = 'ui', version.ref = 'compose_version' }
compose-ui-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview', version.ref = 'compose_version' }
compose-ui-tooling = { group = 'androidx.compose.ui', name = 'ui-tooling', version.ref = 'compose_version' }
compose-ui-junit = { group = 'androidx.compose.ui', name = 'ui-test-junit4', version.ref = 'compose_version' }
compose-material = { group = 'androidx.compose.material', name = 'material', version.ref = 'compose_version' }
compose-activity = 'androidx.activity:activity-compose:1.3.1'

androidx-core-ktx = 'androidx.core:core-ktx:1.6.0'
androidx-core-splash = 'androidx.core:core-splashscreen:1.0.0-alpha02'
androidx-appcompat = 'androidx.appcompat:appcompat:1.3.1'
androidx-lifecycle-runtime-ktx = 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'

android-material = 'com.google.android.material:material:1.4.0'
android-gradle-core = { group = 'com.android.tools.build', name = 'gradle', version.ref = 'gradle_version' }

hilt-android = { group = 'com.google.dagger', name = 'hilt-android', version.ref = 'dagger_version' }
hilt-compiler = { group = 'com.google.dagger', name = 'hilt-compiler', version.ref = 'dagger_version' }
hilt-navigation = { group = 'androidx.hilt', name = 'hilt-navigation-compose', version = '1.0.0-alpha03' }
hilt-gradle-core = { group = 'com.google.dagger', name = 'hilt-android-gradle-plugin', version.ref = 'dagger_version' }

retrofit-core = { group = 'com.squareup.retrofit2', name = 'retrofit', version.ref = 'retrofit_version' }
retrofit-moshi = { group = 'com.squareup.retrofit2', name = 'converter-moshi', version.ref = 'retrofit_version' }
okhttp-interceptor = { group = 'com.squareup.okhttp3', name = 'logging-interceptor', version.ref = 'okhttp_version' }

kotlin-gradle-core = { group = 'org.jetbrains.kotlin', name = 'kotlin-gradle-plugin', version.ref = 'kotlin_version' }

[bundles]

retrofit = ['retrofit-core', 'retrofit-moshi', 'okhttp-interceptor']