[versions]

compose_version = '1.0.2'
kotlin_version = '1.5.21'
gradle_version = '7.1.0-alpha13'

[libraries]

compose-ui-core = { group = 'androidx.compose.ui', name = 'ui', version.ref = 'compose_version' }
compose-ui-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview', version.ref = 'compose_version' }
compose-ui-tooling = { group = 'androidx.compose.ui', name = 'ui-tooling', version.ref = 'compose_version' }
compose-ui-junit = { group = 'androidx.compose.ui', name = 'ui-test-junit4', version.ref = 'compose_version' }
compose-material = { group = 'androidx.compose.material', name = 'material', version.ref = 'compose_version' }
compose-activity = 'androidx.activity:activity-compose:1.3.1'

androidx-core-ktx = 'androidx.core:core-ktx:1.6.0'
androidx-appcompat = 'androidx.appcompat:appcompat:1.3.1'
androidx-lifecycle-runtime-ktx = 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'

android-material = 'com.google.android.material:material:1.4.0'
android-gradle-core = { group = 'com.android.tools.build', name = 'gradle', version.ref = 'gradle_version' }

kotlin-gradle-core = { group = 'org.jetbrains.kotlin', name = 'kotlin-gradle-plugin', version.ref = 'kotlin_version' }

[bundles]